In [2]:
import numpy as np
l=np.random.randint(10,100,20)
l

array([35, 85, 29, 59, 91, 87, 29, 53, 32, 63, 23, 77, 37, 31, 33, 93, 50,
       76, 14, 32])

In [3]:
np.sum(l)

1029

In [4]:
big_array=np.random.randint(100,1000,15)
print(big_array)
big_array.sum(),big_array.min(),big_array.max()

[477 811 126 584 732 890 689 758 159 843 333 976 320 565 574]


(8837, 126, 976)

In [8]:

M=np.random.randint(10,100,(3,4))
print(M)

[[14 69 78 77]
 [85 33 34 19]
 [56 68 21 53]]


In [9]:
M.sum(),M.min(),M.max()

(607, 14, 85)

In [10]:
M.sum(axis=0),M.min(axis=0),M.max(axis=0)

(array([155, 170, 133, 149]), array([14, 33, 21, 19]), array([85, 69, 78, 77]))

In [11]:
M.sum(axis=1),M.min(axis=1),M.max(axis=1)

(array([238, 171, 198]), array([14, 19, 21]), array([78, 85, 68]))

In [16]:
np.product([[1,4],[7,10]])


280

In [18]:
a=np.array([[1,2],[3,4]])
np.mean(a)

2.5

In [19]:
a=np.array([[1,2,3,4],[5,6,7,8]])
np.std(a)

2.29128784747792

In [20]:
a=np.array([[1,2],[3,4]])
np.var(a)

1.25

In [ ]:
  n   