In [1]:
import numpy as np
x=np.sort([3,2,4,5,7])
print(x)

[2 3 4 5 7]


In [2]:
i=np.argsort([0,3,5,7,1])
print(i)

[0 4 1 2 3]


In [3]:
a=np.random.RandomState(42)
x=np.random.randint(0,10,(3,4))
print(x)

[[5 1 6 1]
 [4 8 6 9]
 [7 0 3 3]]


In [5]:
np.sort(x,axis=1)

array([[1, 1, 5, 6],
       [4, 6, 8, 9],
       [0, 3, 3, 7]])

In [6]:
np.sort(x,axis=0)

array([[4, 0, 3, 1],
       [5, 1, 6, 3],
       [7, 8, 6, 9]])

In [7]:
np.sort(-x)

array([[-6, -5, -1, -1],
       [-9, -8, -6, -4],
       [-7, -3, -3,  0]])

In [8]:
np.sort(-x,axis=1)

array([[-6, -5, -1, -1],
       [-9, -8, -6, -4],
       [-7, -3, -3,  0]])

In [9]:
a=np.sort(['chennai','india','mumbai'])
print(a)

['chennai' 'india' 'mumbai']


In [11]:
a=np.sort(['true','false','true'])
print(a)

['false' 'true' 'true']


In [12]:
a=np.sort([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [14]:
arr=np.sort([2,3,4,5,6])
print(arr[0])

2


In [16]:
arr=np.sort([2,3,4,5,6])
print(arr[1]+arr[3])

8


In [17]:
arr=np.sort([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr[0,1])

[3 4]


In [19]:
obj=np.sort([12,90,380,12,211])
print(np.where(obj<12))

(array([], dtype=int64),)


In [20]:
obj=np.sort([12,90,380,12,211])
print(obj)
print(obj.nonzero())

[ 12  12  90 211 380]
(array([0, 1, 2, 3, 4], dtype=int64),)
